"""
System-wide constants for the distributed chat system.
"""

# Network Configuration
BROADCAST_IP = "255.255.255.255"  # Subnet broadcast (works on most LANs)
BROADCAST_PORT = 5972             # Discovery broadcast port
RING_PORT = 10001                 # LCR election ring port (UDP)
CHAT_PORT = 10002                 # Chat message port (UDP)
HEARTBEAT_PORT = 10003            # Heartbeat port (UDP)
TCP_PORT = 10004                  # TCP port for reliable delivery

# Buffer size for UDP
BUFFER_SIZE = 4096

# Timing (seconds)
HEARTBEAT_INTERVAL = 2.0
HEARTBEAT_TIMEOUT = 30.0
ELECTION_TIMEOUT = 5.0
DISCOVERY_INTERVAL = 3.0
RECONNECT_INTERVAL = 5.0
MESSAGE_RETRY_INTERVAL = 1.0
MESSAGE_RETRY_MAX = 5

# Protocol Message Types
MSG_DISCOVERY_ANNOUNCE = "DISCOVERY_ANNOUNCE"
MSG_DISCOVERY_RESPONSE = "DISCOVERY_RESPONSE"
MSG_JOIN_REQUEST = "JOIN_REQUEST"
MSG_JOIN_APPROVED = "JOIN_APPROVED"
MSG_CHAT_MESSAGE = "CHAT_MESSAGE"
MSG_CHAT_ORDERED = "CHAT_ORDERED"
MSG_CHAT_ACK = "CHAT_ACK"
MSG_HEARTBEAT = "HEARTBEAT"
MSG_HEARTBEAT_ACK = "HEARTBEAT_ACK"
MSG_ELECTION = "ELECTION"
MSG_ELECTED = "ELECTED"
MSG_VIEW_CHANGE = "VIEW_CHANGE"
MSG_VIEW_CHANGE_ACK = "VIEW_CHANGE_ACK"
MSG_SYNC_REQUEST = "SYNC_REQUEST"
MSG_SYNC_RESPONSE = "SYNC_RESPONSE"
MSG_CLIENT_DISCONNECT = "CLIENT_DISCONNECT"
MSG_SERVER_SHUTDOWN = "SERVER_SHUTDOWN"
MSG_NACK = "NACK"
MSG_RETRANSMIT = "RETRANSMIT"

# Node Roles
ROLE_SERVER = "SERVER"
ROLE_CLIENT = "CLIENT"
